#!/usr/bin/env python
import traceback
from time import sleep
from datetime import datetime
from time import time as timestamp
import pytz
from hafas_fetcher import HAFASFetcher
from helper import Helper, log
from hosted import CONFIG, DEVICE, NODE

CONFIG.restart_on_update()


def _now():
    tz = pytz.timezone(CONFIG["timezone"])
    now = datetime.utcnow()
    now = now.replace(tzinfo=pytz.utc)
    now = now.astimezone(tz)
    return now


def idle(seconds):
    log("idling for {} seconds".format(seconds))
    timeout = timestamp() + seconds
    while timestamp() < timeout:
        NODE["/time"](Helper.to_unixtimestamp(_now()))
        sleep(1)


def main():
    idle(2)

    while True:
        try:
            stops = CONFIG["stop_ids"].split(",")
            data_sources = CONFIG["data_sources"]
            hafas = HAFASFetcher()
            for stop in stops:
                hafas.fetch_and_parse(stop)
            hafas.sort_and_deduplicate()
            hafas.write_json()

            if CONFIG["api_key"].startswith("http://") or CONFIG["api_key"].startswith(
                "https://"
            ):
                idle(15)
            else:
                if CONFIG["requests_max_per_day"] == -1:
                    sleep_time = 30
                else:
                    requests_per_stop = 2 if data_sources == "both" else 1
                    request_count = len(stops) * requests_per_stop
                    sleep_time = max(
                        86400 / (CONFIG["requests_max_per_day"] / request_count),
                        30,
                    )

                idle(sleep_time)
        except Exception:
            traceback.print_exc()
            sleep(5)


if __name__ == "__main__":
    main()
