name: Code Style

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Dependencies
        run: pip3 install isort
      - name: Run isort
        run: 'isort --check service *.py'
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Dependencies
        run: pip3 install black
      - name: Run black
        run: 'black --check service *.py'
